theme: jekyll-theme-dinky
gems:
  - jekyll-feed
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji

title: MetaImaGen
description: A neuro-structural-genetic analysis powered by ENIGMA